### ISSUE TITLE
SDK roadmap

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-javascript-plugin#3]
Compiled with help of @talkol 

Excluding for now:
- [ ] multifile contracts
- [ ] unit testing

Sanitization:
- [x] functions that can break consensus (Math.rand, new Date(), V8Worker2, ...)
- [x] asynchronous behavior
- [ ] review by @bolshchikov 
- [ ] review by @gilamran 

Contract API:
- [x] exporting functions via ES6 syntax
- [ ] forbid underscored `_functions` from being called from the outside even if they are exported
- [x] type checks via helper functions (`Verify.uint64` and so on)
- [x] events as functions with type checks
- [x] helper functions to transform strings to bytes, bytes to strings, JSON/hex encoding, and so on

Contract Objects:
- [x] Address
- [x] Env
- [ ] Ethereum (not included)
- [ ] Events (needs refactoring of orbs-network-go, check #4)
- [ ] Safemath (not included)
- [x] State
- [x] Service

Data types:
- [x] string
- [x] bytes
- [x] uint32
- [x] uint64

Data types for the future:
- [ ] uint256
- [ ] byte20
- [ ] byte32
- [ ] boolean
